eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: zuul-service

server:
  port: 9081
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: cloud-customer
    api-b:
      path: /api-b/**
      serviceId: cloud-customer